### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by nikhil647** [HugoCapocci/react-download-button#1]
After importing I get this error

/node_modules/react-dfb/lib/create-file-content.js
Module not found: Can't resolve 'base64-arraybuffer' in 'F:\React-Project\pics\node_modules\react-dfb\lib'

**Comment by HugoCapocci** [comment]
My bad... 'base64-arraybuffer' is not supposed to be configured as dev dependency - I'll fix that soon!

**Comment by HugoCapocci** [comment]
@nikhil647 I just published react-dfb@1.0.4 that fix the problem. Please upgrade!  ;)
